Print helpful message for attribute warning

diff --git a/scripts/awestruct b/scripts/awestruct
--- a/scripts/awestruct
+++ b/scripts/awestruct
@@ -10,7 +10,22 @@ else
     }
     if [[ -n "$( grep --fixed-strings WARNING build/error.txt )" ]] ; then
         echo "Failing build due to warnings in log output:" >&2
-        cat build/error.txt >&2
+        sort -u build/error.txt >&2
+
+        if [[ -n "$( grep --fixed-strings 'skipping reference to missing attribute' build/error.txt )" ]] ; then
+          echo
+          echo "NOTE for 'Missing attribut error':"
+          echo "    This means there is a some text that looks like '{some_name}',"
+          echo "    but asciidoctor could not find an attibute called 'some_name'."
+          echo "    If you expected there to be an attribute for substitution,"
+          echo "    check the spelling."
+          echo
+          echo "    To display some literal text such as \${ENV_VAR_NAME}"
+          echo "    you will need to make it a passthrough: +\${ENV_VAR_NAME}+."
+          echo "    To get monospace and passthrough, you must use"
+          echo "    backtick and plus: \`+\${ENV_VAR_NAME}+\`"
+        fi
+
         exit 1
     fi
 fi
